import sqlite3

conn = sqlite3.connect("database.db")
c = conn.cursor()

c.execute("CREATE TABLE ITEMS (ID INTEGER PRIMARY KEY AUTOINCREMENT, TYPE TEXT, NAME TEXT, DESCRIPTION TEXT, COLOUR TEXT, SIZE TEXT, PRICE REAL, BRAND TEXT, RATING REAL)")
c.execute("CREATE TABLE IMAGES (ITEMID INTEGER, IMAGEID INTEGER PRIMARY KEY AUTOINCREMENT, IMAGE BLOB)")



conn.commit()