import sqlite3

conn = sqlite3.connect("database.db")
c = conn.cursor()

c.execute("CREATE TABLE ITEMS (ID INTEGER PRIMARY KEY AUTOINCREMENT, TYPE TEXT, NAME TEXT, DESCRIPTION TEXT, MATERIAL TEXT, PRICE REAL, RATING REAL, QUANTITY INTEGER, PRICE_PER_SWITCH REAL, SWITCH_TYPE TEXT, BRAND TEXT, SIZE TEXT, PCB_INCLUDED BOOLEAN, HOTSWAPPABLE BOOLEAN)")
c.execute("CREATE TABLE IMAGES (ITEMID INTEGER, IMAGEID INTEGER PRIMARY KEY AUTOINCREMENT, IMAGE BLOB)")



conn.commit()